# Generated by Django 5.1.6 on 2025-02-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed At')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
